create table
  public.material_inventory (
    gold integer generated by default 0,
    green_ml integer not null default 0,
    red_ml integer not null default 0,
    blue_ml integer not null default 0,
    dark_ml integer not null default 0,
    constraint material_inventory_pkey primary key (gold)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    sku text not null,
    potion_name text null,
    quantity integer not null default 0,
    price integer not null default 0,
    green integer not null default 0,
    red integer not null default 0,
    blue integer not null default 0,
    dark integer not null default 0,
    id integer generated by default as identity,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id integer generated by default as identity,
    customer_name text null,
    customer_class text null,
    level integer null default 0,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id integer generated by default as identity,
    customer_id integer null,
    item_id integer null,
    quantity integer null,
    constraint cart_items_pkey primary key (id),
    constraint public_cart_items_customer_id_fkey foreign key (customer_id) references carts (id),
    constraint public_cart_items_item_id_fkey foreign key (item_id) references potion_inventory (id)
  ) tablespace pg_default;